---
#inventory file
switches:
  hosts: #change ip addresses to your device ip's
    172.27.18.21:
    172.27.18.22:
    172.27.18.23:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    #username and password as set in device CLI
    ansible_user: admin
    ansible_ssh_pass: cisco123
