---
# inventory file
switches:
  hosts: # change ip addresses to your device ip's
    172.18.6.233:
    172.18.6.234:
    172.18.6.235:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    # username and password as set in device CLI
    ansible_user: admin
    ansible_ssh_pass: cisco123
    dns_servers:
      - 1.1.1.1
      - 8.8.8.8
