---
#creates loopback0 with address 1.1.1.1
- name: Configure loopbacks
  connection: network_cli
  hosts: switches
  gather_facts: false
  tasks:
    - name: Create loopback0
      cisco.ios.ios_config:
        lines:
          - int loopback0
          - ip address 1.1.1.1 255.255.255.255
#saves to startup config
    - name: Save to startup config
      cisco.ios.ios_config:
        save_when: modified
